### ISSUE TITLE
io500-find.sh not working properly

### ISSUE THREAD

**Issue by gflofst** [VI4IO/io-500-dev#11]
I get an error message that the ....100.0 is not found (I am running with 100 total). The code looks like it is trying to do 1-100, but I am guessing it is not working properly. Everything is 1-100 numbered.

**Comment by gmarkomanolis** [comment]
Are talking about the execution of the startup.sh?  Could you provide more information?

Maybe add

#!/bin/bash -x

to check step by step what happens

**Comment by gflofst** [comment]
From what John and I saw, it isn't searching everything. Julian says that is because it would not finish in time for you or him. Rather than weaken the standards, a different suggested tool should be provided that can finish in time. Offering best practices is supposed to be part of the list rather than us weakening the benchmark because it is too hard.

The specific problem I was seeing was it complaining that it could not find an xxxx.100.0 file or directory. It didn't happen the last couple of times I ran though. I'll close this since find is being replaced by John and Julian to something that can do the agreed upon test within timeframes.

**Comment by johnbent** [comment]
Within timeframes may be tough. If mdtest easy and mdtest hard can create more files than the system tools can handle, that suggests a problem with system tools and not the benchmark. 

Maybe five minutes needs to be re-examined.  Especially for mdtest.
