### ISSUE TITLE
prepare.sh needs new repo hash code for combined IOR/mdtest

### ISSUE THREAD

**Issue by gflofst** [VI4IO/io-500-dev#13]
Current one fails.

**Comment by johnbent** [comment]
What error are you seeing?  It works for me:

Cloning into 'ior'...
remote: Counting objects: 750, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 750 (delta 0), reused 2 (delta 0), pack-reused 746
Receiving objects: 100% (750/750), 508.12 KiB | 282.00 KiB/s, done.
Resolving deltas: 100% (473/473), done.
Note: checking out 'e1968cd4ad50d3d5dee853ae3b1a8724f4f072c7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

**Comment by gflofst** [comment]
This script downloads the code for the benchmarks
It will also attempt to build the benchmarks
It will output OK at the end if builds succeed
Cloning into 'ior'...
remote: Counting objects: 750, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 750 (delta 0), reused 2 (delta 0), pack-reused 746
Receiving objects: 100% (750/750), 508.12 KiB | 592.00 KiB/s, done.
Resolving deltas: 100% (473/473), done.
Checking connectivity... done.
Note: checking out 'e1968cd4ad50d3d5dee853ae3b1a8724f4f072c7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e1968cd... Merge pull request #7 from hjelmn/master
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
main::scan_file() called too early to check prototype at /ascldap/users/gflofst/work/redsky/bin/aclocal line 642.
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /ascldap/users/gflofst/work/redsky/bin/autoconf --force
configure.ac:9: error: possibly undefined macro: X_AC_META
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /ascldap/users/gflofst/work/redsky/bin/autoconf failed with exit status: 1

**Comment by johnbent** [comment]
This appears actually to be a problem with the merged IOR / mdtest
repo....  Which worked for at least Glenn, Nathan, and I.

Is it possible you don't have libtool installed?
https://github.com/sanger-pathogens/gubbins/issues/130

**Comment by johnbent** [comment]
While we wait to figure out what broke for Jay in the new IOR/mdtest, we can always check out the old versions:

git clone https://github.com/MDTEST-LANL/mdtest
git clone https://github.com/IOR-LANL/ior

then 'git checkout' these hashes:

MDTEST_HASH=7c0ec411c762d65db137997526b9feca9d2d0046
IOR_HASH=2541bfea7bd6c8d85f928e7f64f55e7ae02b5e3a

**Comment by gmarkomanolis** [comment]
I had a similar with Jay error, not the same, then I was checking around (I am on a Cray machine) and I did just the following:

module load autotools/2.69 

I assume it needs a newer version than the default one of the system?

Finished with success :)

ls -ltr bin/
total 22288
-rwxr-xr-x 1 markomg k01 11328675 Oct 24 08:07 mdtest
-rwxr-xr-x 1 markomg k01 11492140 Oct 24 08:07 ior

**Comment by johnbent** [comment]
Can you add this as an issue in the IOR GitHub please?  Perhaps they need to check libtool version and print an error message if the wrong one.

**Comment by gflofst** [comment]
TOSS does not have autotools anymore (the tri-labs standard OS and libraries setup). I'll have to play with this later. I don't think it is an issue for IOR, but a note we should include so that people know they need newer autotools.

**Comment by johnbent** [comment]
IOR should document their needed tool chain.

**Comment by gmarkomanolis** [comment]
OK I will.

**Comment by johnbent** [comment]
George created an issue with IOR itself about this so I'm closing this here.

**Comment by gflofst** [comment]
The required .m4 file is there, it is a matter that the autoreconf does not have the path properly to get the file into the config directory. Also, cbif.c needs a #define _LARGEFILE64_SOURCE to compile for me.

**Comment by johnbent** [comment]
@gflofst , can we close this now?
