### ISSUE TITLE
pfind should install in bin like the binary executables (also other scripts)

### ISSUE THREAD

**Issue by gflofst** [VI4IO/io-500-dev#15]
We almost have an easy setup. If prepare.sh works (you have the right autotools), then it just needs to add pfind into bin so that you can take bin + io500.sh and copy that to scratch to run. Yes, there are other scripts that need to be copied too, but all of them should be staged to bin. I build in HOME and run in SCRATCH. I think that it typical.

**Comment by johnbent** [comment]
Fixed.  I also had to move ./utilities/find/sfind.sh and ./utilities/find/pfind.sh in there as well.
