### ISSUE TITLE
Need to stop counting MPI launch time in mdtest and pfind

### ISSUE THREAD

**Issue by johnbent** [VI4IO/io-500-dev#18]
Currently the io500_fixed.sh script measures the wall-clock time for mdtest and pfind and uses that to compute the kiops.  For IOR, it greps the wall-clock time out of the IOR results.  It should do the same for mdtest and pfind.  Required changes:
1. modify mdtest, pfind, and sfind.sh to print out wall-clock time
2. modify io500_fixed.sh to parse these and use them instead of its own wall-clock measurement

**Comment by johnbent** [comment]
I wonder however if we actually should count MPI launch time for pfind.  The task is to search the namespace quickly.  If this requires launching MPI, then maybe it should be counted.

MPI launch however clearly shouldn't be considered in mdtest and IOR since they are intended to emulate an IO phase of a running job as opposed to find which is the actual entire job.

**Comment by gmarkomanolis** [comment]
On 3000+ nodes MPI Init could take up to 1-2 minutes, it is important to exclude the initialization time.

**Comment by JulianKunkel** [comment]
The original scripts did use the output from mdtest, via the simple grep
here, e.g

iops4=$(grep "File stat" $result_dir/mdt_hard_stat | tail -n 1 | awk
'{print $4}')



Am 24.10.2017 21:16 schrieb "George Markomanolis" <notifications@github.com

**Comment by johnbent** [comment]
Whoops, you're right.  It still does that exact thing.  It prints a debug
message saying how long it took which uses wall-clock as measured in
io500_fixed.sh.  But the reported IOPs is just from within mdtest.

And, I think it's appropriate to count MPI launch for pfind.  What we are
measuring how long does it take to answer this question:
'find a subset of files from a giant population'
If you have to launch MPI to answer that question, then we should count the
MPI launch time.

I'll close this issue.
