### ISSUE TITLE
md-real-io doesn't build for me with prepare

### ISSUE THREAD

**Issue by johnbent** [VI4IO/io-500-dev#21]
I think we should disable building md-real-io by default since it is optional and we want to minimize the probability of any error during the simple 
>clone
>prepare
>run
workflow.

Here is the error that I'm seeing by the way:

~/io-500-dev
Preparing MD-REAL-IO
~/io-500-dev/build ~/io-500-dev
Cloning into 'md-real-io'...
remote: Counting objects: 581, done.
remote: Total 581 (delta 0), reused 0 (delta 0), pack-reused 581
Receiving objects: 100% (581/581), 214.49 KiB | 984.00 KiB/s, done.
Resolving deltas: 100% (374/374), done.
~/io-500-dev
~/io-500-dev/build/md-real-io ~/io-500-dev
usage: dirname path
getopt: illegal option -- l
Unknown option help,version,debug,reconfigure,prefix:,with-cc:,with-mongoc:,with-mpic++:,with-mpicc:,with-mpi-lib:,with-mpi-include:,with-libs3:,plantuml-jar-dir:,with-mpi:,with-libpq:,verbose,build-dir:,minimal

**Comment by JulianKunkel** [comment]
Let's leave it there, but add || true after building that way the script
runs but Mac users won't have it :)

Am 25.10.2017 19:39 schrieb "John Bent" <notifications@github.com>:

**Comment by johnbent** [comment]
OK.  Good idea.  Done.
