### ISSUE TITLE
Problems with prepare.sh and building

### ISSUE THREAD

**Issue by johnbent** [VI4IO/io-500-dev#24]
I received this email:
====================
i am running RHEL 7.4 clients, so not really something old and the code seems to require cmake 3: 

...
/perform/io-500-dev
/perform/io-500-dev/build/md-real-io /perform/io-500-dev
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.0 or higher is required. You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!
An error occurred during the configuration, aborting!
/perform/io-500-dev
....

but it continue and claims all is ok at the end : 

mpicc -std=gnu99 -g -O2 -o ior ior-ior.o ior-utilities.o ior-parse_options.o ior-aiori.o ior-aiori-MPIIO.o ior-aiori-POSIX.o -lgpfs -lm
make[1]: Entering directory `/perform/io-500-dev/build/ior/src'
make[1]: Nothing to be done for `install-data-am'.
/usr/bin/mkdir -p '/perform/io-500-dev/bin'
/usr/bin/install -c ior mdtest '/perform/io-500-dev/bin'
make[1]: Leaving directory `/perform/io-500-dev/build/ior/src'
IOR: OK

/perform/io-500-dev
/perform/io-500-dev/build/md-real-io/build /perform/io-500-dev/build/md-real-io
make: *** No rule to make target `install'. Stop.
MD-REAL-IO: OK

/perform/io-500-dev/build/md-real-io

OK: All required software packages are now prepared
io500_fixed.sh ior lib mdtest pfind sfind.sh

interestingly enough the binaries are here : 

[root@client01 io-500-dev]# ll bin/
total 2848
-rw-r--r-- 1 root root 11155 Oct 28 14:33 io500_fixed.sh
-rwxr-xr-x 1 root root 1453304 Oct 28 14:34 ior
drwxr-xr-x 2 root root 4096 Oct 28 14:34 lib
-rwxr-xr-x 1 root root 1370224 Oct 28 14:34 mdtest
-rwxr-xr-x 1 root root 6635 Oct 28 14:34 pfind
-rwxr-xr-x 1 root root 1475 Oct 28 14:33 sfind.sh
[root@client01 io-500-dev]#

i am sure i am not the only one who will run into this. 
======================================

**Comment by gmarkomanolis** [comment]
That's strange, but at the end, he has everything built, except mdreal-io, right? Good to know.

**Comment by johnbent** [comment]
Yes. Just errors configuring mdreal. Which then make the ‘make’ fail also.

**Comment by gmarkomanolis** [comment]
ok, the error about cmake is from mdreal, if he uses the appropriate cmake, the mdreal binary is created.

**Comment by adilger** [comment]
The `mdrealio` build was disabled by default with commit d975b6257eb, should this be closed?

**Comment by johnbent** [comment]
Seems like this should be closed. Thanks @adilger
