### ISSUE TITLE
Parallel find

### ISSUE THREAD

**Issue by johnbent** [VI4IO/io-500-dev#3]
It might be nice to create a default MPI-based 'find' command that people who don't have a custom tool can use.  It might be considerably faster than the CLI find.  Note that LANL pftool can almost surely be used as the foundation for this as it has a lot of namespace traversal parallelism already implemented:  https://github.com/pftool/pftool

**Comment by JulianKunkel** [comment]
There exists a simple MPI parallel find now that relies on the local find.
