### ISSUE TITLE
Issue running prepare.sh

### ISSUE THREAD

**Issue by anoriega211** [VI4IO/io-500-dev#59]
Hi,

During the IOR build I hit the following issue:

<...snip...>
checking for linux/lustre/lustre_user.h... no
checking lustre/lustre_user.h usability... no
checking lustre/lustre_user.h presence... no
checking for lustre/lustre_user.h... no
./configure: line 6906: syntax error near unexpected token `newline'
./configure: line 6906: `  yes:no:'

Looking in configure at line 6906 it looks like a case statement with a bad syntax:

6904 # So?  What about this header?
6905 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
6906   yes:no:
6907 fi
6908 

Is there anything I can do to get around this?

Thank you!

**Comment by JulianKunkel** [comment]
Hi Andreas
Can you try to remove the hash from prepare.sh, i.e. build with the newest
IOR as there have been some changes in configure.

Best
Julian

Andres <notifications@github.com> schrieb am Mi., 27. Nov. 2019, 00:46:

**Comment by anoriega211** [comment]
Hi Julian,

Commenting out the hash did the trick! Prepare.sh ran to completion this time. Thank you for the help.

Thanks,
Andres
