### ISSUE TITLE
Cleanup at the end of the script run is bad

### ISSUE THREAD

**Issue by gflofst** [VI4IO/io-500-dev#6]
The $SLURM_NNODES.txt file is not removed. The subtree.cfg is not removed either. The script removes the io500 directory, but it really wants all of the scripts used to run everything really need to be in there too requiring a script to copy the scripts into the directory.

**Comment by johnbent** [comment]
So I just edited.  I got rid of the whole subtree.cfg thing since it isn't in alignment with how the find command needs to run.  And I took out the SLURM stuff too since the default io500.sh shouldn't assume a job scheduler.
