### ISSUE TITLE
mdtest hard write: No space left on device

### ISSUE THREAD

**Issue by abrekhov** [VI4IO/io-500-dev#63]
Hi! 
Job failed on mdtest_hard_write section. Here is log:

```
Command line used: /nfs/hybrilit.jinr.ru/user/r/rsc/io500/2020-spring/io-500-dev/bin/mdtest '-C' '-t' '-F' '-P' '-w' '3901' '-e' '3901' '-d' '/lustre/stor1/rsc/io500/2020-spring/io500.2020.05.17-01.48.52/mdt_hard' '-n' '950000' '-x' '/lustre/stor1/rsc/io500/2020-spring/io500.2020.05.17-01.48.52/mdt_hard-stonewall' '-a' 'POSIX' '-N' '1' '-W' '300'
...
ior ERROR: open64("/lustre/stor1/rsc/io500/2020-spring/io500.2020.05.17-01.48.52/mdt_hard/test-dir.0-0/mdtest_tree.0/file.mdtest.727.10410", 66, 0664) failed, errno 28, No space left on device (aiori-POSIX.c:413)
Abort(-1) on node 727 (rank 727 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 727
```
Should it be less writes per proc?

**Comment by adilger** [comment]
Your directory may be running out of space, or your MDT may be running
out of inodes. You need to enable the "large_dir" feature on the MDT if it is
not enabled yet - "tune2fs -O large_dir <mdtdev>". 

You can check the free inodes count with "lfs df -i" on any client node.
Note that you also need to have enough free inodes on all of the OSTs
as well, unless you are using Data-on-MDT. 

If you are using multiple MDTs, you should add to prepare_directories()
function in io500.sh a command to
set the directories to be striped over all MDTs by default after the existing mkdir command:

    lfs setdirstripe -D -c -1 $io500_datadir 

Cheers, Andreas

**Comment by abrekhov** [comment]
Andreas, thanks for reply!

This is the output of tune2fs. I suppose that it has not been applied. Did I forget something?
```
[root@s01p001 ~]# tune2fs -O large_dir -ff /dev/nvme1n1
tune2fs 1.45.2.wc1 (27-May-2019)
Warning: needs_recovery flag is set. You may wish
replay the journal then rerun this command, or any
changes may be overwritten by journal recovery.
```

**Comment by adilger** [comment]
You can run "dumpe2fs -h /dev/nvme1n1 | grep feature" to see the
features on that filesystem.

Cheers, Andreas

**Comment by abrekhov** [comment]
Probably our MDTs run out of inodes... Thanks for help!
