### ISSUE TITLE
find phase - field name discrepancy between io500.sh logic and io500

### ISSUE THREAD

**Issue by pvaldria** [VI4IO/io-500-dev#66]
io500 (C version) expects a field labelled:  external-extra-args    in the config.ini file,  but the non-C version (io500.sh) logic is looking for field labelled:  “external-args” (without “-extra-“)  , see below line:
https://github.com/VI4IO/io500-app/blob/master/io500.sh#L229

 io500_find_cmd_args="$(get_ini_param find external-args)"

less config-full.ini
```
[find]
# Set to an external script to perform the find phase
external-script =
# Extra arguments for external scripts
external-extra-args =
# Startup arguments for external scripts
external-mpi-args =
# Set the number of processes for pfind
nproc =
# Pfind queue length
pfind-queue-length = 10000
# Pfind Steal from next
pfind-steal-next = FALSE
# Parallelize the readdir by using hashing. Your system must support this!
pfind-parallelize-single-dir-access-using-hashing = FALSE
 
```
**Temporary workaround:**   I changed the io500.sh code to look for:    io500_find_cmd_args="$(get_ini_param find external-extra-args)"

**Comment by adilger** [comment]
This was fixed in the io500-app repo by commit 0da7c14f6e.
