### ISSUE TITLE
metadata tests are requiring 5 minute runs

### ISSUE THREAD

**Issue by gflofst** [VI4IO/io-500-dev#7]
I didn't recall that the MD tests were intended to run for at least 5 minutes as well. Was this intentional?

**Comment by gmarkomanolis** [comment]
There is no need to run for five minutes. For some cases, it just happens.

**Comment by gflofst** [comment]
The script checks for it. I'll adjust the script for my pull request I am creating.

**Comment by gmarkomanolis** [comment]
I think it does check for all the tests, just a warning. Some reported results are done with less than 5 minutes execution time.
