### ISSUE TITLE
find phase: bash version doesn't look at named parameters in .ini file

### ISSUE THREAD

**Issue by carlilek** [VI4IO/io-500-dev#70]
The bash version of the benchmark appears to ignore the parameters under the [find] section of the config.ini file, namely
pfind-steal-next
pfind-queue-length
pfind-parallelize-single-dir-access-using-hashing
nproc

The last of them would probably require a fair amount of extra code to reinterpret the nproc requested to new mpirun_args. 

Evidence: 
`[find]
# Pfind Steal from next
pfind-steal-next = TRUE
# Pfind queue length
pfind-queue-length = 20000
# Pfind with hashing
pfind-parallelize-single-dir-access-using-hashing = TRUE
# Set the number of processes for pfind
#nproc = 900
`

from bash script output:
`[Starting] find
[Exec] mpiexec -np 300 -ppn 30 -f /io500/io500-isc20/io500-app/hostfile-10-h09 --bootstrap ssh /io500/io500-isc20/io500-app/bin/pfind ./datadir/2020.06.01-13.50.21-scr -newer ./datadir/2020.06.01-13.50.21-scr/timestampfile -size 3901c -name "*01*"  `

from C script:
`[find]
t_start         = 2020-06-01 14:11:03
exe             = ./pfind ./datadir/2020.06.01-13.50.21-app -newer ./datadir/2020.06.01-13.50.21-app/timestampfile -size 3901c -name *01* -C -N -H 1 -q 20000`

**Comment by JulianKunkel** [comment]
Could you fill them into the "external-extra-args" section? This relates to #66, an unofficial bugfix is available in the app master.

**Comment by carlilek** [comment]
Yes, I suspect that would be a functional temporary workaround. I'm not seeing exactly where the parameters would need to be translated for the bash version (I think the io500.sh calls io500-fixed.sh directly, so I guess it would need to be there?)

On Jun 1, 2020, at 2:35 PM, Julian Kunkel <notifications@github.com<mailto:notifications@github.com>> wrote:



Could you fill them into the "external-extra-args" section? This relates to #66<https://urldefense.com/v3/__https://github.com/VI4IO/io-500-dev/issues/66__;!!Eh6p8Q!UasW6FyNSVH0TIb2AvqewXBMTqXLvMYyL6UyIEiU6PYboe-6KX8T9MShm8VTa-Xt9LzM$>, an unofficial bugfix is available in the app master.

**Comment by JulianKunkel** [comment]
Basically, the external-extra-args would then support:
pfind-steal-next
pfind-queue-length
pfind-parallelize-single-dir-access-using-hashing

However, nproc won't be supported at all, in #66, I wrote that spawning a
bash from an MPI process that executes MPI doesn't necessarily work. With
current OpenMPI it doesn't anymore. Therefore, needs a changed/new pfind
using the same API.

**Comment by johnbent** [comment]
Can't you write a wrapper to pfind that is called by just rank 0 and it itself spawns a new MPI job?
________________________________

**Comment by JulianKunkel** [comment]
I tried to do this. Didn't work any more with current OpenMPI. I searched
in google for popen and found some issues revolving around that only mpi
spawn can be used.

John Bent <notifications@github.com> schrieb am Mo., 1. Juni 2020, 19:57:

**Comment by carlilek** [comment]
Putting the flags (aside from nproc) into the external-extra-args does appear to work as a workaround. What I did for nproc in prior seasons was to "replace" the pfind command with the full mpirun -ppn -np blah -blah -blah pfind. I don't think that would work in this case because the C app has the mpirun command baked in.

**Comment by carlilek** [comment]
Ah, so external-extra-args would then only apply to the bash script, while I would need to keep the matching C options in the ini file as well. That explains the find portion of the results I submitted yesterday and this morning.

--Ken

On Jun 1, 2020, at 2:36 PM, Carlile, Ken <carlilek@janelia.hhmi.org<mailto:carlilek@janelia.hhmi.org>> wrote:

Yes, I suspect that would be a functional temporary workaround. I'm not seeing exactly where the parameters would need to be translated for the bash version (I think the io500.sh calls io500-fixed.sh directly, so I guess it would need to be there?)

On Jun 1, 2020, at 2:35 PM, Julian Kunkel <notifications@github.com<mailto:notifications@github.com>> wrote:



Could you fill them into the "external-extra-args" section? This relates to #66<https://urldefense.com/v3/__https://github.com/VI4IO/io-500-dev/issues/66__;!!Eh6p8Q!UasW6FyNSVH0TIb2AvqewXBMTqXLvMYyL6UyIEiU6PYboe-6KX8T9MShm8VTa-Xt9LzM$>, an unofficial bugfix is available in the app master.

**Comment by carlilek** [comment]
This appears to be an issue with the ISC20 version of io500-app (github.com/VI4IO/io-500-app) rather than -dev, as it's an issue with the pre-processing in the io500.sh of that package. I will close this issue here and open a new one over there.
