### ISSUE TITLE
Quibbling about the composite scores...

### ISSUE THREAD

**Issue by RayLucchesi** [VI4IO/io-500-dev#77]
It's unclear to me why you included the EASY IOR and EASY MD results in the composite scores. If you just used the HARD versions of each (including the EASY FIND). The rankings would be slightly different. 

Also. I understand using why using geomean for all the IOR  and all the MD (+easy FIND), makes sense but do you believe it makes any sense to then take the geomean of these two for your composite score. It's seems more accurate to me that the geomean(all_IOR) and geomean(all_MD) represent two axis(s) of storage performanc,  and that something that took the cartesian distance from origin would be better than taking the geomean of the two values.

**Comment by gflofst** [comment]
I think this was addressed by the issue 76 response. If not, reopen.
