### ISSUE TITLE
The complete CSV link in the 10-node list home page is wrong

### ISSUE THREAD

**Issue by RayLucchesi** [VI4IO/io-500-dev#79]
it appears to be the same as the ISC/SC500 complete list CSV file not one that is just the 10-node list.

here is the link https://www.vi4io.org/assets/io500/2020-07/data.csv and it has as the 1st entry the 52 node Wolf-Intel-DAOS system. not the 10 node Wolf-Intel-DAOS system.

**Comment by JulianKunkel** [comment]
Thanks for reporting, the link is now updated on the webpage to the correct
location:
https://www.vi4io.org/assets/io500/2020-07/data-10.csv
